apiVersion: v1
kind: Service
metadata:
  name: angular-app
  labels:
    app: angular-app
spec:
  selector:
    app: angular-app
  type: LoadBalancer
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP 